### ISSUE TITLE
plugin api

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/github-base#11]
I'm thinking for it. I guess that is also in your mind because I seen `github-base` org.

It should be something that you can add only custom methods to the base.
For example

``` js
var Github = require('github-base')
var github = new Github()
var  fork = require('github-base-fork')

var app = github.use(fork())

// https://developer.github.com/v3/repos/forks/#create-a-fork
app.fork('user/repo', cb)

// https://developer.github.com/v3/repos/forks/#list-forks
app.forks('user/repo', cb) // list forks
```

and for other API endpoints.

Another plugin can be only handling all "creating" things like this one ([i've did it before few months](https://github.com/tunnckoCore/github-create))

``` js
var Github = require('github-base')
var github = new Github()
var  create = require('github-base-create')
var  list = require('github-base-list')

var app = github.use(create()).use(list())

// https://developer.github.com/v3/issues/#create-an-issue
app.issue('user/repo') // or maybe better would be `app.create.issue`
app.issues('user/repo') // => list repo issues

// https://developer.github.com/v3/issues/labels/#create-a-label
app.label('user/repo')
app.labels('user/repo') // => list repo labels

// https://developer.github.com/v3/repos/#create
app.repo('user/repo')
app.repos('user')  // => list user repos
```

and etc?

I think we should start it in some point in future. If you thought it, count me in `github-base` org. :)

/cc but we should finalize #7 before all. Btw, today I playing with that and basically all works, except `.getAll` thing.

**Comment by tunnckoCore** [comment]
For starting, for basic i think `use` will do the job, because plugins will need just the `app` (this)

**Comment by jonschlinkert** [comment]
I thought I already implemented `use` on this repo. let's do that.

**Comment by tunnckoCore** [comment]
Hm. Or leave this as is and create plugin for `base` that just implements `github-base.request` method then we can build other plugins like the above examples on top ot `base-request` (or something)?

Because i believe `base-request` (or other name) could be only this one (it works)

``` js
var utils = require('../lib/utils')
var simpleGet = require('simple-get')
var concat = require('concat-stream')
var extend = require('extend-shallow')

function requestPlugin (config) {
  return function plugin (app) {
    if (this.isRegistered('base-request')) return

    this.define('request', function (method, path, data, cb) {
      if (typeof data === 'function') {
        cb = data
        data = null
      }

      cb = typeof cb === 'function' ? cb : function noop () {}

      var defaults = utils.defaults(extend({
        json: true,
        apiurl: 'https://api.github.com'
      }, this.options, config))

      opts = defaults(method, path, data)

      simpleGet(opts, function (err, res) {
        if (err) {return cb(err)}
        res.pipe(concat(function (data) {
          data = data.toString()
          if (data && data.length && opts.json === true) {
            data = JSON.parse(data)
          }
          cb(null, data, res)
        }))
      })
      return this
    })
  }
}

var Base = require('base')
var app = new Base()

app
  .use(requestPlugin(/* {apiurl: 'http://api.youtube.com'} */))
  .request('GET', '/users/:owner/gists', {owner: 'jonschlinkert'}, function (err, res) {
    console.log(err, res)
  })
```

And `base-request` is good name, cuz it could be more general request + interpolation lib which in turns can be used to build plugins on top of it for other APIs.

**Comment by tunnckoCore** [comment]
``` js
function forksPlugin (config) {
  return function plugin (app) {
    this.define('fork', function (path, data, cb) {
      path = typeof path === 'string' ? path : ':owner/:repo'
      return this.request('POST', '/repos/' + path + '/forks', data, cb)
    })
    this.define('forks', function (path, data, cb) {
      path = typeof path === 'string' ? path : ':owner/:repo'
      return this.request('GET', '/repos/' + path + '/forks', data, cb)
    })
  }
}

var Base = require('base')
var app = new Base()

app
  .use(requestPlugin())
  .use(forksPlugin())
  .request('GET', '/users/:owner/gists', {owner: 'jonschlinkert'}, function (err, res) {
    console.log(err, res.length)
  })
  .forks('jonschlinkert/github-base', function (err, res) {
    console.log(err, res.length)
  })

```

huh, would be pretty cool and pretty fun and easy.

---

Or even we can extend/merge `data`, `config` and `this.options or this.data` to have some defaults, or if someone want defaults for placeholders

**Comment by jonschlinkert** [comment]
not a bad idea, but I'm still thinking that adding `.use` to this would be good, so you can create plugins without having to use `base`. although I'm not sure if we'd need to do anything to the `.get` method if it was used with base. hmm

**Comment by tunnckoCore** [comment]
> although I'm not sure if we'd need to do anything to the .get method if it was used with base. hmm

that's why i think that if we build `base-request` and the other "request" plugins should be namespaced to not have conflicts with core `base` methods. For example `gists` plugin for base should add `app.gists` object that will contain `gists` methods like `app.gists.all()`, `app.gists.starred()`

> but I'm still thinking that adding

mm yea :+1:  i can try to PR when have more time

**Comment by jonschlinkert** [comment]
> plugins should be namespaced to not have conflicts with core

good idea. that's worked well with the other methods.

no rush

**Comment by tunnckoCore** [comment]
little bit spam, lol
