### ISSUE TITLE
Request Headers

### ISSUE THREAD

**Issue by jbbn** [jonschlinkert/github-base#21]
Hi! There is anyway to pass HTTP request headers?

I did a raw* implementation of github api, and I passed a "If-None-Match" to use some cache if the return of the HTTP response status is 304.

I would like to use https://github.com/doowb/github-content, but I need to keep the feature of caching.

(* with "raw" I mean, without any libs)

**Comment by tunnckoCore** [comment]
From what I remember, you can just pass `headers` to the options. It might not be in the docs but I'm pretty sure I've added it on the implementation back then.

**Comment by tunnckoCore** [comment]
Oh yup. It's there, look around a bit in the `utils.js` file.

This "feature" is also used in some of the tests, like [seen here](https://github.com/jonschlinkert/github-base/blob/master/test/post.js#L19-L21)

**Comment by jbbn** [comment]
Really great @tunnckoCore!

I thought it was a obvious try, probably I would test something in the weekend, supposing that should work like this. Today I was out of time.

Really thanks for quite fast response. :pray:

(I'm just a little sad because I've thinked that this could be a "good first issue" to contribute; but I also happy seeing the maturity of the project :rocket:)

**Comment by tunnckoCore** [comment]
Haha, no problem, worth the try.
There's always something to be done.

In this case you can do a PR for adding docs ;p Note that they are generated from code comments and readme comes from the .verb.md file.

Let us know if anything more is needed to help do it.

**Comment by jbbn** [comment]
Fair! It could be in the docs :man_student: 

I'll make a PR trying to expose this and give my scenario as an example. (Indeed, use etags is a good solution, since Github provides it by default for files :1st_place_medal: )

Thanks Charlike! @tunnckoCore
