### ISSUE TITLE
and again, use `simple-get`

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/github-base#3]
I definitely realized that it's better to use `simple-get` plus `concat-stream`. It's really small and really better and even smaller than `github-request` huh.
And return `callback(err, buffer, stream)` without JSON.parse, cuz Github have endpoints that not return JSON, like `/markdown` and it crash when you try to do that. Returning `buffer` instead of JSON.parse(res) would free us up. Also giving the readable `stream` is  good thing.

Another thing is duplication of defaulting `opts.apiurl` and sending everything from `data` to the body of the request. Which isn't okey for me. Like, now it's possible to define placeholders, headers, body, method and etc stuff through `data` from `.post(path, data, cb)`, but you also pass them to the body of the request e.g.

``` js
var data = {
  owner: 'jonschlinkert',
  repo: 'github-base',
  headers: {
    foobar: 'baz'
  },
  title: 'foo bar',
  body: 'baz qux @chorks woohoo'
  body: {
    bar: 'qux'
  }
}
github.post('/repos/:owner/:repo/issues', data, console.log)
```

All that `data` would be stringified and send to the request (from the index.js .request() directly to github-request pkg), from which only 2 fields are needed for request body.

And here can view another problem. What means that `body`, because some endpoints expect that parameter, like above example - "Create an issue" endpoint. But in the `utils.js` in the one if you check that `data` exist, in the other that `opts.body` exist - which actually is `data.body` because the extend.

And exposing token or username+password directly to the server request... don't think so.

---

Other than that.. it's awesome, as always!

**Comment by jonschlinkert** [comment]
all good points, sorry you did some work on this that didn't get merged in, I already had most of the refactoring done. I think you're right about simple-get, I'd be happy to merge that in if you want to do a pr.

**Comment by jonschlinkert** [comment]
fwiw, because of the scope and amount of things I need to get accomplished, I try as hard as I can to make libs awesome - but I don't have as much time as I'd like to explore every possible alternative. So I really appreciate the feedback and help.

**Comment by tunnckoCore** [comment]
> sorry you did some work on this that didn't get merged in, I already had most of the refactoring done.

Yea, it's normal, no problem.

> I'd be happy to merge that in if you want to do a pr.

:+1: 

>  but I don't have as much time as I'd 

same here lol

**Comment by tunnckoCore** [comment]
@jonschlinkert okey, it's ready! :tada: 
I'll PR when add tests and cover 100% coverage with test api server. :)

**Comment by jonschlinkert** [comment]
:+1:

**Comment by tunnckoCore** [comment]
so... closing this, because #4 merged -- Thanks!

/cc @jonschlinkert release and publish

**Comment by jonschlinkert** [comment]
oops meant to click comment. it's on the way
