### ISSUE TITLE
TODO: update tests

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/github-base#6]
Update tests so the `fake-user123` user is not needed.

**Comment by tunnckoCore** [comment]
why and how? ;d i think it's needed for some requests.

Another thing can be to pass different `opts.apiurl` for example to http://httpbin.org or hmm.. nope.

**Comment by doowb** [comment]
There are ways to fake network requests and return values that we might expect. I think this is a better way to run the tests so we don't have to hit github and store fake user credentials with the project.

I've done this with the `request` module when using the `.get` method, but I haven't looked into how to do it with `simple-get` yet.

**Comment by jonschlinkert** [comment]
tests have been updated in 0.5.0
